// HTTP response codes
export const COD_RESPONSE_HTTP_OK = 200;
export const COD_RESPONSE_HTTP_CREATED = 201;
export const COD_RESPONSE_HTTP_ACCEPTED = 202;
export const COD_RESPONSE_HTTP_BAD_REQUEST = 400;
export const COD_RESPONSE_HTTP_UNAUTHORIZED = 401;
export const COD_RESPONSE_HTTP_FORBIDDEN = 403;
export const COD_RESPONSE_HTTP_NOT_FOUND = 404;
export const COD_RESPONSE_HTTP_ERROR = 500;
